### ISSUE TITLE
ApiKey isn't sent with extra GET during Backbone.sync

### ISSUE THREAD

**Issue by ngsilverman** [PaulUithol/backbone-tastypie#18]
Backbone's sync is overridden specifically to do a GET upon receiving a HTTP CREATED but when that occurs and if you are using an ApiKey it is not sent along resulting in a 401 Unauthorized response from the server.

**Comment by cvuong** [comment]
I am having this same issue. The options for the ApiKey are not sent to the server.

**Comment by PaulUithol** [comment]
Yep, of course. Should be fixed now.

**Comment by herrmendez** [comment]
Same thing has been happening to me... but maybe I'm doing something wrong. I'm setting it up like this and I can see the data shows up in the console, but I get the 401 when I try posting.

`Backbone.Tastypie.csrfToken = $("#secret-token")[0].value;
Backbone.Tastypie.apiKey = {
    username: USER,
    key: API_KEY
};`

Please let me know of any necessary extra info (I don't really know how to see what information is being sent to check if the api_key + username is being sent in the headers)

**Comment by herrmendez** [comment]
actually, here's the request: http://pastebin.com/GeLxKHqD it's being sent but somehow still get the 401

**Comment by PaulUithol** [comment]
That'd mean the problem is server-side, somewhere in the Python code?

**Comment by herrmendez** [comment]
Not sure, when I do it with curl it seems to work (curl --dump-header - -H "Content-Type: application/json" -X POST --data '{"question": "Is a test yo?", "pub_date": "2011-05-22T00:46:38"}' "http://localhost:8000/polls/api/v1/poll/?username=federico&api_key=10a2d3586e63078ef39f9da8f9aa9209715ed282")
